sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

matrix:
  include:
  - env: BUILD_TYPE=Debug
  - env: BUILD_TYPE=Release
    
before_install:
  - docker build -t ubuntu ./docker
  - docker run --name "ubuntu-test" -d -v $(pwd):/root/catkin_ws/src/arc_utilities -w /root/catkin_ws ubuntu tail -f /dev/null
  - docker ps

install:
  - $SH ". /opt/ros/kinetic/setup.bash && cd ~/catkin_ws && catkin_make_isolated -DCMAKE_BUILD_TYPE=$BUILD_TYPE"

script:
  - $SH ". /root/catkin_ws/devel_isolated/setup.bash && cd ~/catkin_ws && catkin_make_isolated -DCMAKE_BUILD_TYPE=$BUILD_TYPE --catkin-make-args run_tests && catkin_test_results"

after_script:
  - docker images
